# IQL DDPG+BC + AMO α_E, L_E only. No π_B.
# alpha_E=1, alpha_lr=0.0003
defaults:
  alpha_E: 1
  alpha_lr: 0.0003
  expectile: 0.7
  const_std: true
  gaussian: true
  meta_warmup_steps: 100000
  meta_interval: 20
  final_eval_repeats: 5
antmaze:
  expectile: 0.9
  reward_transform: antmaze_shift
  eval_episodes: 100
environments:
  hopper-medium-v2:
    reward_transform: return_range
  hopper-medium-replay-v2:
    reward_transform: return_range
  hopper-medium-expert-v2:
    expectile: 0.5
    reward_transform: return_range
  walker2d-medium-v2:
    reward_transform: return_range
  walker2d-medium-replay-v2:
    reward_transform: return_range
  walker2d-medium-expert-v2:
    reward_transform: return_range
  halfcheetah-medium-v2:
    reward_transform: return_range
  halfcheetah-medium-replay-v2:
    reward_transform: return_range
  halfcheetah-medium-expert-v2:
    reward_transform: return_range
